version: "3.9"

services:
  diabetes-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: cs317-diabetes_api
    depends_on:
      - prometheus
      # - fluentd
    # command: >
    #   sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./logging:/logging
    logging:
      driver: "json-file"

  prometheus:
    image: prom/prometheus
    container_name: cs317-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle" 
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager
    container_name: cs317-alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml  
    command:
      - "--config.file=/etc/alertmanager/config.yml"
    ports:
      - "9093:9093"


  grafana:
    image: grafana/grafana
    container_name: cs317-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin


  node_exporter:
    image: prom/node-exporter
    container_name: cs317-node_exporter
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:2.9.0
    container_name: cs317-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/data:/loki        
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:2.9.0
    container_name: cs317-promtail
    volumes:
      - ./logging:/logging
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki
