fluentd:
  image: fluent/fluentd
  volumes:
    - ./fluentd/conf:/fluentd/etc
    - /var/log:/var/log      # syslog
    - ./logs:/app/logs       # app log
  ports:
    - "24224:24224"
    - "24224:24224/udp"
